services:
  - type: web
    name: shopsage-backend
    env: python
    region: oregon
    plan: free
    rootDir: OnlineBoutiqueAgent/ecommerce_agent
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: POETRY_VERSION
        value: ""
      - key: DISABLE_POETRY_CREATE_RUNTIME_FILE
        value: "1"
      - key: GOOGLE_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
